"""
Notification system — sends email alerts for new NYPD contracts.
"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from contractmonitor.config import Config
from contractmonitor.models import Contract

logger = logging.getLogger(__name__)


def send_notification(contracts: list[Contract], config: Config) -> bool:
    """Send an email notification about new NYPD contracts found."""
    if not contracts:
        return True

    if not config.smtp_user or not config.notify_to:
        # Print to console as fallback
        logger.warning("Email not configured — printing to console")
        print_notification(contracts)
        return True

    subject = f"🚨 {len(contracts)} New NYPD Contract(s) Found"
    body_html = _build_html(contracts)
    body_text = _build_text(contracts)

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = config.notify_from or config.smtp_user
        msg["To"] = config.notify_to

        msg.attach(MIMEText(body_text, "plain"))
        msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP(config.smtp_host, config.smtp_port) as server:
            server.starttls()
            server.login(config.smtp_user, config.smtp_password)
            server.send_message(msg)

        logger.info(f"Notification sent to {config.notify_to}: {len(contracts)} contracts")
        return True

    except Exception as e:
        logger.error(f"Email notification failed: {e}")
        print_notification(contracts)
        return False


def print_notification(contracts: list[Contract]) -> None:
    """Print contracts to console."""
    print("\n" + "=" * 70)
    print(f"  NYPD CONTRACT ALERT — {len(contracts)} new item(s) found")
    print("=" * 70)
    for i, c in enumerate(contracts, 1):
        print(f"\n--- #{i} ---")
        print(c.summary())
    print("\n" + "=" * 70 + "\n")


def _build_text(contracts: list[Contract]) -> str:
    lines = [
        f"NYPD Contract Alert — {len(contracts)} new item(s) found",
        "=" * 50,
        "",
    ]
    for i, c in enumerate(contracts, 1):
        lines.append(f"#{i}")
        lines.append(c.summary())
        lines.append("")
    return "\n".join(lines)


def _build_html(contracts: list[Contract]) -> str:
    rows = ""
    for c in contracts:
        rows += f"""
        <tr>
            <td style="padding:8px;border:1px solid #ddd;">
                <a href="{c.url}">{c.title}</a>
            </td>
            <td style="padding:8px;border:1px solid #ddd;">{c.source}</td>
            <td style="padding:8px;border:1px solid #ddd;">{c.agency}</td>
            <td style="padding:8px;border:1px solid #ddd;">{c.contract_type}</td>
            <td style="padding:8px;border:1px solid #ddd;">{c.posted_date}</td>
            <td style="padding:8px;border:1px solid #ddd;">{c.amount}</td>
            <td style="padding:8px;border:1px solid #ddd;">{c.vendor}</td>
        </tr>"""

    return f"""
    <html>
    <body style="font-family:Arial,sans-serif;">
    <h2>NYPD Contract Alert</h2>
    <p>{len(contracts)} new contract(s) or posting(s) detected:</p>
    <table style="border-collapse:collapse;width:100%;">
        <thead>
            <tr style="background:#003366;color:white;">
                <th style="padding:8px;border:1px solid #ddd;">Title</th>
                <th style="padding:8px;border:1px solid #ddd;">Source</th>
                <th style="padding:8px;border:1px solid #ddd;">Agency</th>
                <th style="padding:8px;border:1px solid #ddd;">Type</th>
                <th style="padding:8px;border:1px solid #ddd;">Posted</th>
                <th style="padding:8px;border:1px solid #ddd;">Amount</th>
                <th style="padding:8px;border:1px solid #ddd;">Vendor</th>
            </tr>
        </thead>
        <tbody>{rows}</tbody>
    </table>
    <p style="color:#666;font-size:12px;margin-top:20px;">
        Generated by NYPD Contract Monitor
    </p>
    </body>
    </html>
    """
